@baseUrl = http://localhost:3000

 @userId = 6a54ceb92f5dae243a5d65c6

### TEST API
GET {{baseUrl}}

### CREATE USER
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doae",
  "email": "roman0090@example.com",
  "password": "test123"
}

### GET ALL USERS
GET {{baseUrl}}/users

### GET USER BY ID
GET {{baseUrl}}/users/{{userId}}

### UPDATE USER BY ID
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "John Doe Updated"
}

### DELETE USER BY ID
DELETE {{baseUrl}}/users/{{userId}}


#### REGISTER USER
POST {{baseUrl}}/auth/register
Content-Type: application/json  

{
  "name": "Jane Doe",
  "email": "jane.diie007@example.com",
  "password": "test123"
}

### LOGIN USER
POST {{baseUrl}}/auth/login
Content-Type: application/json  

{
  "email": "jane.diie007@example.com",
  "password": "test123"
}
