@baseUrl = http://localhost:3000

@userId = 6a4ce88aabab13630a183530

### TEST API
GET {{baseUrl}}

### CREATE USER
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe8@example.com",
  "password": "test123"
}

### GET ALL USERS
GET {{baseUrl}}/users

### GET USER BY ID
GET {{baseUrl}}/users/{{userId}}

### UPDATE USER BY ID
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "John Doe Updated"
}

### DELETE USER BY ID
DELETE {{baseUrl}}/users/{{userId}}